### ISSUE TITLE
crash when loading mangrove chunk

### ISSUE THREAD

**Issue by anim4trix** [ItsBlackGear/TheWildBackport-Master#14]
Description: Ticking entity

java.lang.IllegalArgumentException: Cannot get property class_2746{name=hanging, clazz=class java.lang.Boolean, values=[true, false]} as it does not exist in Block{wildbackport:mud}
	at net.minecraft.class_2688.method_11654(class_2688.java:98)
	at com.cursedcauldron.wildbackport.common.blocks.MangrovePropaguleBlock.isHanging(MangrovePropaguleBlock.java:116)
	at com.cursedcauldron.wildbackport.common.blocks.MangrovePropaguleBlock.method_9558(MangrovePropaguleBlock.java:68)
	at net.minecraft.class_1542.handler$gle010$vanillatweaks$tick(class_1542.java:3078)
	at net.minecraft.class_1542.method_5773(class_1542.java:99)
	at net.minecraft.class_3218.method_18762(class_3218.java:702)
	at net.minecraft.class_1937.method_18472(class_1937.java:485)
	at net.minecraft.class_3218.method_31420(class_3218.java:363)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:331)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:907)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:851)
	at net.minecraft.class_1132.method_3748(class_1132.java:97)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:273)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by anim4trix** [comment]
culprit is vanillatweaks
